### PR TITLE
Dank stuff for Markos + a rewrite

### PR DESCRIPTION
**Pull request by CrimsonXV**

### CODE REVIEW

**Comment by CrimsonXV** [comment]
ayyyyyy

**Comment by melmsie** [comment]
aayyyyyyyyyyyy

**Comment by CrimsonXV** [comment]
lmao

**Comment by Samoxive** [comment]
fuck it, we will do it live

**Comment by CrimsonXV** [comment]
wat

**Comment by CrimsonXV** [comment]
aw yiss guess who just got their changes committed #FeelsGoodMan

**Comment by melmsie** [comment]
Sounds like an ERB reference

**Comment by CrimsonXV** [comment]
a wat reference

**Pull request merged**
